Add Agents Support to SDK
mindsdb/mindsdb_python_sdk pull request #96
Opened 2024-04-12 05:00 UTC by tmichaeldb

Fixes RAG-26.

Depends on changes in [#9067](https://github.com/mindsdb/mindsdb/pull/9067)

This PR adds support for creating & using agents from underlying MindsDB Langchain models. Currently, only text-to-SQL is supported. A follow-up PR will add a retrieval skill for RAG functionality.

See `/examples/using_agents.py` for example usage:
```python
import mindsdb_sdk

con = mindsdb_sdk.connect()

# We currently support Langchain as a backend.
print('Creating underlying langchain model for the agent to use...')
try:
    langchain_engine = con.ml_engines.get('langchain')
except Exception:
    # Create the engine if it doesn't exist.
    langchain_engine = con.ml_engines.create('langchain', handler='langchain')

# Actually create the underlying model the agent will use.
langchain_model = con.models.create(
    'agent_model',
    predict='answer',
    engine='langchain',
    prompt_template='You are a spicy, cheeky assistant. Add some personality and flare when responding to the user question: {{question}}',
    model_name='gpt-4-0125-preview' # This is the underlying LLM. Can use OpenAI, Claude, local Ollama, etc
    # Can optionally set LLM args here. For example:
    # temperature=0.0,
    # max_tokens=1000,
    # top_p=1.0,
    # top_k=0,
    # ...
)
print('Agent ready to use.')

# Now create an agent that will use the model we just created.
agent = con.agents.create('new_agent', langchain_model)
print('Ask a question: ')
question = input()
answer = agent.completion([{'question': question, 'answer': None}])
print(answer.content)
```

2024-04-13 07:16 UTC, ea-rus commented
I've merged #97. Now if you update this branch from staging - CI should be fine

2024-04-13 07:43 UTC, ea-rus requested changes

2024-04-13 07:43 UTC, ea-rus commented on mindsdb_sdk/agents.py
> +        if self.name != other.name:
how this method should be used. in which use-case user compares this objects? 
if it is required: from mindsdb server perspective two agents can't have the same name in one project. So name-project_name is already unique identifier.

2024-04-13 07:43 UTC, ea-rus commented on mindsdb_sdk/agents.py
> +    """Collection for agents"""
He have documentation [autogenerated](https://mindsdb.github.io/mindsdb_python_sdk/) from docstrings. 
Would be great to have here (and in Skills class) some brief info how to use it. 
Examples from other classes [1](https://github.com/mindsdb/mindsdb_python_sdk/blob/628a7c7d1494ac7e045472a4e08ad90eafd2ed09/mindsdb_sdk/views.py#L38), [2](https://github.com/mindsdb/mindsdb_python_sdk/blob/06202aea36d67823c53b16f979e40dfd711e5439/mindsdb_sdk/tables.py#L179)

2024-04-13 07:43 UTC, ea-rus commented on tests/test_sdk.py
> +            skills=[Skill('test_skill', 'test', {'k1': 'v1'})],
Maybe to forbid to use generic Skill and force the user to use specific skill: SQLSkill or KBSkill ?
It helps to send only required params.

2024-04-16 08:34 UTC, ea-rus commented
I've added some fixes for tests and docs, CI works now

2024-04-16 08:58 UTC, ea-rus commented on tests/test_sdk.py
> +            skills=[Skill('test_skill', 'test', {'k1': 'v1'})],
For now (when we don't have all wrappers for all skills) we could keep to use just generic Skill class

2024-04-16 09:03 UTC, ea-rus commented on mindsdb_sdk/agents.py
> +        if self.name != other.name:
The main idea: skill and agent can be identified by name (and project), we can't have the same name in one project. So we don't need to compare all columns to check if it is the same object in mindsdb. 
If the purpose is only for tests (to compare result with expectation) we could move this comparator to tests (also we can do it later)

2024-04-16 12:59 UTC, dusvyat approved these changes
nice looks good to me

2024-04-16 13:26 UTC, ea-rus commented on mindsdb_sdk/agents.py
> +    def delete(self, name: str):
could we rename this method to 'drop' for consistency with methods for other entities in SDK API (and for skills too) ?

2024-04-16 16:41 UTC, ea-rus approved these changes

2024-04-16 21:57 UTC, merged